import type { Report } from "./types";

function list(items?: string[], marker = "-"): string {
  return (items ?? []).map((i) => `${marker} ${i}`).join("\n");
}

/** Render the full briefing as a readable Markdown document for download. */
export function reportToMarkdown(report: Report): string {
  const { synthesis, sections } = report;
  const { mission_values, benefits, business_ops, leadership, news, red_flags } =
    sections;

  const md = `# ${report.profile?.canonical_name || report.company} — Interview Research Briefing
${report.role ? `**Target role:** ${report.role}\n` : ""}${
    report.profile?.domain ? `**Company website:** ${report.profile.domain}\n` : ""
  }
Generated by ScoutOne on ${new Date().toLocaleDateString()}.

> Note: the company score rates the company from public web signals — it is not
> a measure of your personal fit. Verify claims via the sources in each section.

## Executive summary

${synthesis?.executive_summary ?? ""}

- **Company score:** ${synthesis?.overall_score ?? "—"}/100
- **Analyst read:** ${synthesis?.recommendation ?? ""}

### Dimension scores

${(synthesis?.scores ?? [])
  .map((s) => `- **${s.dimension}: ${s.score}/100** — ${s.reason}`)
  .join("\n")}

## 1. Mission, values & culture

${mission_values?.mission ?? ""}

### Core values

${(mission_values?.core_values ?? [])
  .map((v) => `- **${v.value}** — ${v.meaning}`)
  .join("\n")}

### Culture

${mission_values?.culture_summary ?? ""}

### Ask yourself

${list(mission_values?.values_alignment_questions)}

### Talking points

${list(mission_values?.talking_points)}

Sources:
${list(mission_values?.sources)}

## 2. Employee benefits

${(benefits?.benefits ?? [])
  .map((b) => `### ${b.category}\n\n${list(b.items)}`)
  .join("\n\n")}

### Compensation

${benefits?.compensation_notes ?? ""}

### Work-life balance

${benefits?.work_life_balance ?? ""}

### Standout perks

${list(benefits?.standout_perks)}

### Questions to ask

${list(benefits?.questions_to_ask)}

Sources:
${list(benefits?.sources)}

## 3. Business operations

${business_ops?.what_they_do ?? ""}

- **Employees:** ${business_ops?.scale?.employees ?? "—"}
- **Headquarters:** ${business_ops?.scale?.headquarters ?? "—"}
- **Founded:** ${business_ops?.scale?.founded ?? "—"}
- **Revenue:** ${business_ops?.scale?.revenue ?? "—"}

### Business model

${business_ops?.business_model ?? ""}

### Key products & services

${(business_ops?.key_products ?? [])
  .map((p) => `- **${p.name}** — ${p.description}`)
  .join("\n")}

### Market position

${business_ops?.market_position ?? ""}

**Competitors:** ${(business_ops?.competitors ?? []).join(", ")}

### Growth trajectory

${business_ops?.growth_trajectory ?? ""}

### Business-savvy questions

${list(business_ops?.smart_questions)}

Sources:
${list(business_ops?.sources)}

## 4. Leadership

${(leadership?.leaders ?? [])
  .map(
    (l) =>
      `### ${l.name} — ${l.title}\n\n${l.background}\n\n${l.notable ? `> ${l.notable}` : ""}`
  )
  .join("\n\n")}

### Leadership style

${leadership?.leadership_style ?? ""}

### Public vision

${list(leadership?.vision_statements)}

### Recent changes

${leadership?.recent_changes ?? ""}

### How to use this

${leadership?.interview_angle ?? ""}

Sources:
${list(leadership?.sources)}

## 5. News & recent events

${news?.big_picture ?? ""}

${(news?.headlines ?? [])
  .map(
    (h) =>
      `- **${h.title}**${h.date ? ` (${h.date})` : ""} — _${h.sentiment}_\n  ${h.summary}${h.url ? `\n  ${h.url}` : ""}`
  )
  .join("\n")}

### Conversation starters

${list(news?.conversation_starters)}

Sources:
${list(news?.sources)}

## 6. Red flag scan

**Overall risk level:** ${red_flags?.risk_level ?? "—"}

${(red_flags?.red_flags ?? [])
  .map(
    (f) =>
      `- **${f.flag}** (severity: ${f.severity}, ${f.pattern_or_isolated}) — ${f.detail}`
  )
  .join("\n")}

### Green flags

${list(red_flags?.green_flags)}

### Verdict

${red_flags?.verdict ?? ""}

### Diplomatic questions to probe

${list(red_flags?.questions_to_probe)}

Sources:
${list(red_flags?.sources)}

## Interview cheat sheet

### 30-second elevator pitch

> ${synthesis?.elevator_pitch ?? ""}

### Best questions to ask them

${list(synthesis?.top_questions_to_ask)}

### Prep checklist

${(synthesis?.prep_checklist ?? []).map((i, n) => `${n + 1}. ${i}`).join("\n")}
`;
  return md.replace(/\n{3,}/g, "\n\n");
}

export function downloadFile(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
