import jsPDF from "jspdf";
import type { Report } from "./types";

const RED = "#e63946";
const TEAL = "#2a9d8f";
const YELLOW_DARK = "#b8860b"; // readable yellow on white paper
const INK = "#111111";
const GRAY = "#555555";

const PAGE_W = 595; // A4 portrait, points
const PAGE_H = 842;
const MARGIN = 52;
const WIDTH = PAGE_W - MARGIN * 2;

/** Text-based PDF briefing built from the same structured data as the UI. */
export function reportToPdf(report: Report): void {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  let y = MARGIN;

  function pageBreak(needed: number) {
    if (y + needed > PAGE_H - MARGIN) {
      doc.addPage();
      y = MARGIN;
    }
  }

  function heading(text: string, size: number, color: string, gapAbove = 14) {
    pageBreak(size + gapAbove + 8);
    y += gapAbove;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(size);
    doc.setTextColor(color);
    const lines: string[] = doc.splitTextToSize(text, WIDTH);
    for (const line of lines) {
      pageBreak(size * 1.3);
      doc.text(line, MARGIN, y);
      y += size * 1.3;
    }
  }

  function para(text?: string, opts?: { color?: string; size?: number; indent?: number; bold?: boolean }) {
    if (!text) return;
    const size = opts?.size ?? 10;
    const indent = opts?.indent ?? 0;
    doc.setFont("helvetica", opts?.bold ? "bold" : "normal");
    doc.setFontSize(size);
    doc.setTextColor(opts?.color ?? INK);
    const lines: string[] = doc.splitTextToSize(text, WIDTH - indent);
    for (const line of lines) {
      pageBreak(size * 1.45);
      doc.text(line, MARGIN + indent, y);
      y += size * 1.45;
    }
    y += 3;
  }

  function bullets(items?: string[], marker = "•") {
    for (const item of items ?? []) {
      para(`${marker}  ${item}`, { indent: 8 });
    }
  }

  function labelValue(label: string, value?: string) {
    if (!value) return;
    pageBreak(15);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(INK);
    doc.text(`${label}: `, MARGIN, y);
    const labelWidth = doc.getTextWidth(`${label}: `);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(GRAY);
    const lines: string[] = doc.splitTextToSize(value, WIDTH - labelWidth);
    doc.text(lines[0] ?? "", MARGIN + labelWidth, y);
    y += 14.5;
    for (const line of lines.slice(1)) {
      pageBreak(14.5);
      doc.setTextColor(GRAY);
      doc.text(line, MARGIN, y);
      y += 14.5;
    }
  }

  function sources(urls?: string[]) {
    const valid = (urls ?? []).filter((u) => /^https?:\/\//i.test(u));
    if (!valid.length) return;
    para("Sources:", { color: GRAY, size: 8.5, bold: true });
    for (const url of valid) para(url, { color: GRAY, size: 8 , indent: 8 });
  }

  const { synthesis, sections } = report;
  const { mission_values, benefits, business_ops, leadership, news, red_flags } =
    sections;

  // ===== Title =====
  heading(
    `${report.profile?.canonical_name || report.company} — Interview Research Briefing`,
    20,
    RED,
    0,
  );
  if (report.role) para(`Target role: ${report.role}`, { color: GRAY, size: 11 });
  if (report.profile?.domain)
    para(`Company website: ${report.profile.domain}`, { color: GRAY, size: 11 });
  para(`Generated by ScoutOne on ${new Date().toLocaleDateString()}.`, {
    color: GRAY,
    size: 9,
  });
  para(
    "Note: the company score rates the company from public web signals only — it is not a measure of your personal fit. Verify claims via the sources in each section.",
    { color: GRAY, size: 8.5 }
  );

  // ===== Executive summary =====
  heading("Executive summary", 14, TEAL);
  para(synthesis?.executive_summary);
  labelValue("Company score", `${synthesis?.overall_score ?? "—"}/100`);
  labelValue("Analyst read", synthesis?.recommendation);
  heading("Dimension scores", 11, INK, 8);
  for (const s of synthesis?.scores ?? []) {
    para(`•  ${s.dimension}: ${s.score}/100 — ${s.reason}`, { indent: 8 });
  }

  // ===== 1. Mission & values =====
  heading("1. Mission, values & culture", 14, TEAL);
  para(mission_values?.mission);
  heading("Core values", 11, INK, 8);
  for (const v of mission_values?.core_values ?? []) {
    para(`•  ${v.value} — ${v.meaning}`, { indent: 8 });
  }
  heading("Culture", 11, INK, 8);
  para(mission_values?.culture_summary);
  heading("Ask yourself", 11, INK, 8);
  bullets(mission_values?.values_alignment_questions);
  heading("Talking points", 11, INK, 8);
  bullets(mission_values?.talking_points);
  sources(mission_values?.sources);

  // ===== 2. Benefits =====
  heading("2. Employee benefits", 14, TEAL);
  for (const b of benefits?.benefits ?? []) {
    heading(b.category, 11, INK, 8);
    bullets(b.items);
  }
  heading("Compensation", 11, INK, 8);
  para(benefits?.compensation_notes);
  heading("Work-life balance", 11, INK, 8);
  para(benefits?.work_life_balance);
  heading("Standout perks", 11, INK, 8);
  bullets(benefits?.standout_perks, "★");
  heading("Questions to ask", 11, INK, 8);
  bullets(benefits?.questions_to_ask);
  sources(benefits?.sources);

  // ===== 3. Business operations =====
  heading("3. Business operations", 14, TEAL);
  para(business_ops?.what_they_do);
  labelValue("Employees", business_ops?.scale?.employees);
  labelValue("Headquarters", business_ops?.scale?.headquarters);
  labelValue("Founded", business_ops?.scale?.founded);
  labelValue("Revenue", business_ops?.scale?.revenue);
  heading("Business model", 11, INK, 8);
  para(business_ops?.business_model);
  heading("Key products & services", 11, INK, 8);
  for (const p of business_ops?.key_products ?? []) {
    para(`•  ${p.name} — ${p.description}`, { indent: 8 });
  }
  heading("Market position", 11, INK, 8);
  para(business_ops?.market_position);
  labelValue("Competitors", (business_ops?.competitors ?? []).join(", "));
  heading("Growth trajectory", 11, INK, 8);
  para(business_ops?.growth_trajectory);
  heading("Business-savvy questions", 11, INK, 8);
  bullets(business_ops?.smart_questions);
  sources(business_ops?.sources);

  // ===== 4. Leadership =====
  heading("4. Leadership", 14, TEAL);
  for (const l of leadership?.leaders ?? []) {
    heading(`${l.name} — ${l.title}`, 11, INK, 8);
    para(l.background);
    if (l.notable) para(`Worth referencing: ${l.notable}`, { color: YELLOW_DARK });
  }
  heading("Leadership style", 11, INK, 8);
  para(leadership?.leadership_style);
  heading("Public vision", 11, INK, 8);
  bullets(leadership?.vision_statements);
  heading("Recent changes", 11, INK, 8);
  para(leadership?.recent_changes);
  heading("How to use this", 11, INK, 8);
  para(leadership?.interview_angle);
  sources(leadership?.sources);

  // ===== 5. News =====
  heading("5. News & recent events", 14, TEAL);
  para(news?.big_picture);
  for (const h of news?.headlines ?? []) {
    para(`•  ${h.title}${h.date ? ` (${h.date})` : ""} — ${h.sentiment}`, {
      indent: 8,
      bold: true,
    });
    para(h.summary, { indent: 16, color: GRAY });
    if (h.url) para(h.url, { indent: 16, color: GRAY, size: 8 });
  }
  heading("Conversation starters", 11, INK, 8);
  bullets(news?.conversation_starters);
  sources(news?.sources);

  // ===== 6. Red flags =====
  heading("6. Red flag scan", 14, RED);
  labelValue("Overall risk level", red_flags?.risk_level);
  if (red_flags?.red_flags?.length) {
    for (const f of red_flags.red_flags) {
      para(`•  ${f.flag} (severity: ${f.severity}, ${f.pattern_or_isolated})`, {
        indent: 8,
        bold: true,
        color: RED,
      });
      para(f.detail, { indent: 16, color: GRAY });
    }
  } else {
    para("No significant red flags surfaced in the scan.", { color: TEAL });
  }
  heading("Green flags", 11, INK, 8);
  bullets(red_flags?.green_flags, "✓");
  heading("Verdict", 11, INK, 8);
  para(red_flags?.verdict);
  heading("Diplomatic questions to probe", 11, INK, 8);
  bullets(red_flags?.questions_to_probe);
  sources(red_flags?.sources);

  // ===== Cheat sheet =====
  heading("Interview cheat sheet", 14, TEAL);
  heading("30-second elevator pitch", 11, INK, 8);
  para(`"${synthesis?.elevator_pitch ?? ""}"`);
  heading("Best questions to ask them", 11, INK, 8);
  bullets(synthesis?.top_questions_to_ask);
  heading("Prep checklist", 11, INK, 8);
  (synthesis?.prep_checklist ?? []).forEach((item, i) => {
    para(`${i + 1}.  ${item}`, { indent: 8 });
  });

  // Page footers
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(GRAY);
    doc.text(`ScoutOne · ${report.company}`, MARGIN, PAGE_H - 28);
    doc.text(`${i} / ${pages}`, PAGE_W - MARGIN, PAGE_H - 28, { align: "right" });
  }

  doc.save(
    `${report.company.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}-briefing.pdf`
  );
}
